name: "Podcast Generator"
author: "Richard Myles"
description: "Generates a feed for a podcast from a YMAL file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The commiter's emails address
    required: true
    default: ${{ github.actior }}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.actor }}
