FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y curl\
    python3.10\
    python3-pip \
    git

RUN --force-reinstall pip3 pyYAML

COPY feed.py /usr/bin/feed.py

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
